!obj:pylearn2.train.Train {
 dataset: !obj:pylearn2.datasets.csv_dataset.CSVDataset &train {
  path: '/home/dean/git/kaggle/forest_cover/train_mlp.csv',
  one_hot: 1
 },
 model: !obj:pylearn2.models.mlp.MLP {
  layers: [ 
   !obj:pylearn2.models.mlp.RectifiedLinear {
    layer_name: 'h0',
    dim: 1200,
    sparse_init: 15
   }, !obj:pylearn2.models.mlp.Softmax {
    layer_name: 'y',
    n_classes: 7,
    irange: 0.05
   }
  ],
  nvis: 55
 },
 algorithm : !obj:pylearn2.training_algorithms.sgd.SGD {
  batch_size: 100,
  learning_rate: .01,
  monitoring_dataset: {
   'train': *train,
   'valid': !obj:pylearn2.datasets.csv_dataset.CSVDataset {
     path: '/home/dean/git/kaggle/forest_cover/valid_mlp.csv',
     one_hot: 1
   },
   'test': !obj:pylearn2.datasets.csv_dataset.CSVDataset {
     path: '/home/dean/git/kaggle/forest_cover/test_mlp.csv',
     one_hot: 1
   }
  },
  cost : !obj:pylearn2.costs.cost.SumOfCosts { costs : [
    !obj:pylearn2.costs.mlp.Default {
    }, !obj:pylearn2.costs.mlp.WeightDecay {
      coeffs: [ .00005, .00005 ]
    }
  ]},
#  cost: !obj:pylearn2.costs.mlp.dropout.Dropout {
#    default_input_include_prob : .8 ,
#    default_input_scale: 1.,
#  },
  learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
   init_momentum : .5
  },
  termination_criterion: !obj:pylearn2.termination_criteria.And {
   criteria: [
    !obj:pylearn2.termination_criteria.MonitorBased {
     channel_name: "valid_y_misclass",
     prop_decrease : 0.,
     N : 10
    },
    !obj:pylearn2.termination_criteria.EpochCounter {
     max_epochs: 10000
    }
   ]
  }
 },
 extensions : [ 
  !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
   channel_name: "valid_y_misclass",
   save_path: "mlp2.pkl"
  },
  !obj:pylearn2.training_algorithms.learning_rule.MomentumAdjustor {
   start: 1,
   saturate: 10,
   final_momentum: .99
  }
 ]
}