!obj:pylearn2.train.Train {
 dataset: !obj:pylearn2.datasets.csv_dataset.CSVDataset &train {
  path: '/home/dean/git/kaggle/forest_cover/train_dataset.csv',
  one_hot: 1
 },
 model: !obj:pylearn2.models.softmax_regression.SoftmaxRegression {
  n_classes: 7,
  irange: 0.,
  nvis: 105
 },
 algorithm : !obj:pylearn2.training_algorithms.bgd.BGD {
  batch_size: 10000,
  line_search_mode: 'exhaustive',  
  conjugate: 1,
  updates_per_batch: 10,
  monitoring_dataset: {
   'train': *train,
   'valid': !obj:pylearn2.datasets.csv_dataset.CSVDataset {
     path: '/home/dean/git/kaggle/forest_cover/valid_dataset.csv',
     one_hot: 1
   }
  },
  termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
    channel_name: "valid_y_misclass"
  }
 }
}